services:
  guarden-images:
    image: rustfs/rustfs:latest
    container_name: guarden_images
    restart: unless-stopped
    environment:
      ENV_CORS_ALLOWED_ORIGINS: ${PUBLIC_URL}
    volumes:
      - guarden_images:/data
    ports:
      - ${GD_STORAGE_PORT}:9000
      - ${GD_STORAGE_ADMIN_PORT}:9001
    networks:
      - guarden-network

  guarden-db:
    image: postgres:latest
    container_name: guarden_database
    restart: unless-stopped
    volumes:
      - guarden_pgdata:/var/lib/postgresql
    ports:
      - ${GD_DB_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - guarden-network

  adminer:
    container_name: guarden_db_debug
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - guarden-network

  api-core:
    image: ghcr.io/sellnat77/guarden/api-core:latest
    container_name: guarden_api_core
    build:
      context: "api-core"
    ports:
      - ${GD_SERVER_PORT}:5000
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      GD_DB_HOST: ${GD_DB_HOST}
      GD_DB_PORT: ${GD_DB_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      OBJECT_STORAGE_SERVER: ${OBJECT_STORAGE_SERVER}
      PUBLIC_OBJECT_STORAGE_SERVER: ${PUBLIC_OBJECT_STORAGE_SERVER}
      PUBLIC_URL: ${PUBLIC_URL}
    depends_on:
      - guarden-db
      - guarden-images
    networks:
      - guarden-network

  dashboard:
    image: ghcr.io/sellnat77/guarden/dashboard:latest
    container_name: guarden_dashboard
    build:
      context: "dashboard"
    ports:
      - ${GD_DASHBOARD_PORT}:3000
    environment:
      VITE_GD_GRAPHQL_SERVER: ${VITE_GD_GRAPHQL_SERVER}
    depends_on:
      - api-core
    networks:
      - guarden-network

networks:
  guarden-network:
    driver: bridge

volumes:
  guarden_pgdata:
  guarden_images:
