"""Remove plant cascade

Revision ID: 830af94dd1b1
Revises: a83ac3d0d4de
Create Date: 2026-03-01 09:29:19.418408

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "830af94dd1b1"
down_revision: Union[str, Sequence[str], None] = "a83ac3d0d4de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
