"""Add delete cascades

Revision ID: a83ac3d0d4de
Revises: ec36a3d4c421
Create Date: 2026-02-06 11:59:00.392039

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a83ac3d0d4de"
down_revision: Union[str, Sequence[str], None] = "ec36a3d4c421"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("plants_createdById_fkey"), "plants", type_="foreignkey")
    op.drop_constraint(op.f("plants_locationId_fkey"), "plants", type_="foreignkey")
    op.create_foreign_key(
        None, "plants", "users", ["createdById"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "plants", "locations", ["locationId"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("vitals_plantId_fkey"), "vitals", type_="foreignkey")
    op.create_foreign_key(
        None, "vitals", "plants", ["plantId"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vitals", type_="foreignkey")
    op.create_foreign_key(
        op.f("vitals_plantId_fkey"), "vitals", "plants", ["plantId"], ["id"]
    )
    op.drop_constraint(None, "plants", type_="foreignkey")
    op.drop_constraint(None, "plants", type_="foreignkey")
    op.create_foreign_key(
        op.f("plants_locationId_fkey"), "plants", "locations", ["locationId"], ["id"]
    )
    op.create_foreign_key(
        op.f("plants_createdById_fkey"), "plants", "users", ["createdById"], ["id"]
    )
    # ### end Alembic commands ###
