"""Add profile picture column

Revision ID: d777ccaf25bb
Revises: 830af94dd1b1
Create Date: 2026-03-10 18:25:09.599597

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d777ccaf25bb"
down_revision: Union[str, Sequence[str], None] = "830af94dd1b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("profilePicture", sa.String(length=255), nullable=False)
    )
    op.alter_column(
        "users",
        "password",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=500),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_column("users", "profilePicture")
    # ### end Alembic commands ###
