/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AddVitalRouteImport } from './routes/add-vital'
import { Route as AddPlantRouteImport } from './routes/add-plant'
import { Route as AddLocationRouteImport } from './routes/add-location'
import { Route as IndexRouteImport } from './routes/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AddVitalRoute = AddVitalRouteImport.update({
  id: '/add-vital',
  path: '/add-vital',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPlantRoute = AddPlantRouteImport.update({
  id: '/add-plant',
  path: '/add-plant',
  getParentRoute: () => rootRouteImport,
} as any)
const AddLocationRoute = AddLocationRouteImport.update({
  id: '/add-location',
  path: '/add-location',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-location': typeof AddLocationRoute
  '/add-plant': typeof AddPlantRoute
  '/add-vital': typeof AddVitalRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-location': typeof AddLocationRoute
  '/add-plant': typeof AddPlantRoute
  '/add-vital': typeof AddVitalRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-location': typeof AddLocationRoute
  '/add-plant': typeof AddPlantRoute
  '/add-vital': typeof AddVitalRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-location'
    | '/add-plant'
    | '/add-vital'
    | '/dashboard'
    | '/login'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-location'
    | '/add-plant'
    | '/add-vital'
    | '/dashboard'
    | '/login'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/add-location'
    | '/add-plant'
    | '/add-vital'
    | '/dashboard'
    | '/login'
    | '/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddLocationRoute: typeof AddLocationRoute
  AddPlantRoute: typeof AddPlantRoute
  AddVitalRoute: typeof AddVitalRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-vital': {
      id: '/add-vital'
      path: '/add-vital'
      fullPath: '/add-vital'
      preLoaderRoute: typeof AddVitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-plant': {
      id: '/add-plant'
      path: '/add-plant'
      fullPath: '/add-plant'
      preLoaderRoute: typeof AddPlantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-location': {
      id: '/add-location'
      path: '/add-location'
      fullPath: '/add-location'
      preLoaderRoute: typeof AddLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddLocationRoute: AddLocationRoute,
  AddPlantRoute: AddPlantRoute,
  AddVitalRoute: AddVitalRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
