/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AddPlantRouteImport } from './routes/add-plant'
import { Route as AddLocationRouteImport } from './routes/add-location'
import { Route as IndexRouteImport } from './routes/index'

const AddPlantRoute = AddPlantRouteImport.update({
  id: '/add-plant',
  path: '/add-plant',
  getParentRoute: () => rootRouteImport,
} as any)
const AddLocationRoute = AddLocationRouteImport.update({
  id: '/add-location',
  path: '/add-location',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-location': typeof AddLocationRoute
  '/add-plant': typeof AddPlantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-location': typeof AddLocationRoute
  '/add-plant': typeof AddPlantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-location': typeof AddLocationRoute
  '/add-plant': typeof AddPlantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-location' | '/add-plant'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-location' | '/add-plant'
  id: '__root__' | '/' | '/add-location' | '/add-plant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddLocationRoute: typeof AddLocationRoute
  AddPlantRoute: typeof AddPlantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/add-plant': {
      id: '/add-plant'
      path: '/add-plant'
      fullPath: '/add-plant'
      preLoaderRoute: typeof AddPlantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-location': {
      id: '/add-location'
      path: '/add-location'
      fullPath: '/add-location'
      preLoaderRoute: typeof AddLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddLocationRoute: AddLocationRoute,
  AddPlantRoute: AddPlantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
