/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAddVitalRouteImport } from './routes/_authenticated/add-vital'
import { Route as AuthenticatedAddPlantRouteImport } from './routes/_authenticated/add-plant'
import { Route as AuthenticatedAddLocationRouteImport } from './routes/_authenticated/add-location'
import { Route as AuthenticatedPlantPlantIdDetailRouteImport } from './routes/_authenticated/plant/$plantId.detail'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAddVitalRoute = AuthenticatedAddVitalRouteImport.update({
  id: '/add-vital',
  path: '/add-vital',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAddPlantRoute = AuthenticatedAddPlantRouteImport.update({
  id: '/add-plant',
  path: '/add-plant',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAddLocationRoute =
  AuthenticatedAddLocationRouteImport.update({
    id: '/add-location',
    path: '/add-location',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlantPlantIdDetailRoute =
  AuthenticatedPlantPlantIdDetailRouteImport.update({
    id: '/plant/$plantId/detail',
    path: '/plant/$plantId/detail',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/add-location': typeof AuthenticatedAddLocationRoute
  '/add-plant': typeof AuthenticatedAddPlantRoute
  '/add-vital': typeof AuthenticatedAddVitalRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/plant/$plantId/detail': typeof AuthenticatedPlantPlantIdDetailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/add-location': typeof AuthenticatedAddLocationRoute
  '/add-plant': typeof AuthenticatedAddPlantRoute
  '/add-vital': typeof AuthenticatedAddVitalRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/plant/$plantId/detail': typeof AuthenticatedPlantPlantIdDetailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/add-location': typeof AuthenticatedAddLocationRoute
  '/_authenticated/add-plant': typeof AuthenticatedAddPlantRoute
  '/_authenticated/add-vital': typeof AuthenticatedAddVitalRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/plant/$plantId/detail': typeof AuthenticatedPlantPlantIdDetailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/add-location'
    | '/add-plant'
    | '/add-vital'
    | '/dashboard'
    | '/plant/$plantId/detail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/add-location'
    | '/add-plant'
    | '/add-vital'
    | '/dashboard'
    | '/plant/$plantId/detail'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/add-location'
    | '/_authenticated/add-plant'
    | '/_authenticated/add-vital'
    | '/_authenticated/dashboard'
    | '/_authenticated/plant/$plantId/detail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/add-vital': {
      id: '/_authenticated/add-vital'
      path: '/add-vital'
      fullPath: '/add-vital'
      preLoaderRoute: typeof AuthenticatedAddVitalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/add-plant': {
      id: '/_authenticated/add-plant'
      path: '/add-plant'
      fullPath: '/add-plant'
      preLoaderRoute: typeof AuthenticatedAddPlantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/add-location': {
      id: '/_authenticated/add-location'
      path: '/add-location'
      fullPath: '/add-location'
      preLoaderRoute: typeof AuthenticatedAddLocationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plant/$plantId/detail': {
      id: '/_authenticated/plant/$plantId/detail'
      path: '/plant/$plantId/detail'
      fullPath: '/plant/$plantId/detail'
      preLoaderRoute: typeof AuthenticatedPlantPlantIdDetailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAddLocationRoute: typeof AuthenticatedAddLocationRoute
  AuthenticatedAddPlantRoute: typeof AuthenticatedAddPlantRoute
  AuthenticatedAddVitalRoute: typeof AuthenticatedAddVitalRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPlantPlantIdDetailRoute: typeof AuthenticatedPlantPlantIdDetailRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAddLocationRoute: AuthenticatedAddLocationRoute,
  AuthenticatedAddPlantRoute: AuthenticatedAddPlantRoute,
  AuthenticatedAddVitalRoute: AuthenticatedAddVitalRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPlantPlantIdDetailRoute: AuthenticatedPlantPlantIdDetailRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
