"""Create a baseline migrations

Revision ID: 25feb43f9b35
Revises: 
Create Date: 2026-04-12 10:15:12.903703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25feb43f9b35'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('FULL_SUN', 'BRIGHT', 'PARTIAL', 'SHADY', 'LOW', 'DARK', 'ZERO', name='lightRequirements').create(op.get_bind())
    sa.Enum('HEALTHY', 'STRESSED', 'DISEASED', 'PEST_INFESTED', 'NUTRIENT_DEFICIENT', 'WATER_STRESSED', 'ROOT_BOUND', 'WILTING', 'FOLIAR_BURN', 'SICKLY_YELLOW_LEAVES', 'BROWN_EDGES', 'FLOWER_DROP', 'SLOW_GROWTH', 'LEAF_SPOT', name='generalHealth').create(op.get_bind())
    sa.Enum('FULL_SUN', 'BRIGHT', 'PARTIAL', 'SHADY', 'LOW', 'DARK', 'ZERO', name='lightProvided').create(op.get_bind())
    op.create_table('tips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipText', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('profilePicture', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lightProvided', postgresql.ENUM('FULL_SUN', 'BRIGHT', 'PARTIAL', 'SHADY', 'LOW', 'DARK', 'ZERO', name='lightProvided', create_type=False), nullable=False),
    sa.Column('avgTemp', sa.Integer(), nullable=False),
    sa.Column('avgHumidity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=250), nullable=True),
    sa.Column('indoors', sa.Boolean(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('species', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('generalHealth', postgresql.ENUM('HEALTHY', 'STRESSED', 'DISEASED', 'PEST_INFESTED', 'NUTRIENT_DEFICIENT', 'WATER_STRESSED', 'ROOT_BOUND', 'WILTING', 'FOLIAR_BURN', 'SICKLY_YELLOW_LEAVES', 'BROWN_EDGES', 'FLOWER_DROP', 'SLOW_GROWTH', 'LEAF_SPOT', name='generalHealth', create_type=False), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('lightRequirements', postgresql.ENUM('FULL_SUN', 'BRIGHT', 'PARTIAL', 'SHADY', 'LOW', 'DARK', 'ZERO', name='lightRequirements', create_type=False), nullable=False),
    sa.Column('waterFrequencyDays', sa.Integer(), nullable=False),
    sa.Column('fertilizeFrequencyDays', sa.Integer(), nullable=False),
    sa.Column('pruneFrequencyDays', sa.Integer(), nullable=False),
    sa.Column('repotFrequencyDays', sa.Integer(), nullable=False),
    sa.Column('lastWatered', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lastPruned', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lastFertilized', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lastRepotted', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locationId', sa.Integer(), nullable=False),
    sa.Column('createdById', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['createdById'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['locationId'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vitals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('healthPct', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('plantId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plantId'], ['plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vitals')
    op.drop_table('plants')
    op.drop_table('locations')
    op.drop_table('users')
    op.drop_table('tips')
    sa.Enum('FULL_SUN', 'BRIGHT', 'PARTIAL', 'SHADY', 'LOW', 'DARK', 'ZERO', name='lightProvided').drop(op.get_bind())
    sa.Enum('HEALTHY', 'STRESSED', 'DISEASED', 'PEST_INFESTED', 'NUTRIENT_DEFICIENT', 'WATER_STRESSED', 'ROOT_BOUND', 'WILTING', 'FOLIAR_BURN', 'SICKLY_YELLOW_LEAVES', 'BROWN_EDGES', 'FLOWER_DROP', 'SLOW_GROWTH', 'LEAF_SPOT', name='generalHealth').drop(op.get_bind())
    sa.Enum('FULL_SUN', 'BRIGHT', 'PARTIAL', 'SHADY', 'LOW', 'DARK', 'ZERO', name='lightRequirements').drop(op.get_bind())
    # ### end Alembic commands ###
