"""Add generalHealthEnum correctly

Revision ID: 301470ea38d7
Revises: 53b8e3710b3b
Create Date: 2026-03-29 10:45:55.418711

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "301470ea38d7"
down_revision: Union[str, Sequence[str], None] = "53b8e3710b3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="generalHealth",
        new_values=[
            "HEALTHY",
            "STRESSED",
            "DISEASED",
            "PEST_INFESTED",
            "NUTRIENT_DEFICIENT",
            "WATER_STRESSED",
            "ROOT_BOUND",
            "WILTING",
            "FOLIAR_BURN",
            "SICKLY_YELLOW_LEAVES",
            "BROWN_EDGES",
            "FLOWER_DROP",
            "SLOW_GROWTH",
            "LEAF_SPOT",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="plants", column_name="generalHealth"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="generalHealth",
        new_values=[],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="plants", column_name="generalHealth"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
