"""Add owner to Locations

Revision ID: 53b8e3710b3b
Revises: 3f39ad7571e0
Create Date: 2026-03-24 21:15:33.968493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b8e3710b3b'
down_revision: Union[str, Sequence[str], None] = '3f39ad7571e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('userId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'locations', 'users', ['userId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_column('locations', 'userId')
    # ### end Alembic commands ###
