"""Add lightReqs and lightProvided

Revision ID: ae35d01d18b9
Revises: 301470ea38d7
Create Date: 2026-03-29 10:59:16.645922

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ae35d01d18b9"
down_revision: Union[str, Sequence[str], None] = "301470ea38d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "locations",
        sa.Column(
            "lightProvided",
            postgresql.ENUM(
                "FULL_SUN",
                "BRIGHT",
                "PARTIAL",
                "SHADY",
                "LOW",
                "DARK",
                "ZERO",
                name="lightProvided",
                create_type=False,
            ),
            nullable=False,
        ),
    )
    op.alter_column(
        "plants",
        "lightRequirements",
        existing_type=sa.INTEGER(),
        type_=sa.Enum(
            "FULL_SUN",
            "BRIGHT",
            "PARTIAL",
            "SHADY",
            "LOW",
            "DARK",
            "ZERO",
            name="lightRequirements",
        ),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "plants",
        "lightRequirements",
        existing_type=sa.Enum(
            "FULL_SUN",
            "BRIGHT",
            "PARTIAL",
            "SHADY",
            "LOW",
            "DARK",
            "ZERO",
            name="lightRequirements",
        ),
        type_=sa.INTEGER(),
        nullable=True,
    )
    op.drop_column("locations", "lightProvided")
    # ### end Alembic commands ###
